# Nouveau/Nova must be blacklisted here as well besides the initrd to avoid
# delayed loading (for example on Optimus laptops where the Nvidia card is not
# driving the main display).

blacklist nouveau
blacklist nova-core

# Enable complete power management. From:
# file:///usr/share/doc/nvidia-driver/html/powermanagement.html

options nvidia NVreg_TemporaryFilePath=/var/tmp
options nvidia NVreg_EnableS0ixPowerManagement=1
options nvidia NVreg_PreserveVideoMemoryAllocations=1

# The default memory management mode is "driver" (CDMM).
# Uncomment the following line to switch to the previous default of NUMA.

# options nvidia NVreg_CoherentGPUMemoryMode="numa"
